# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "TwitchBot"
primary_region = "sin" # This is server location

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1 # after deploying, you can use command "fly scale" to set machine number
  processes = ["app"]
